### ISSUE TITLE
Stereo linking not working properly

### ISSUE THREAD

**Issue by rikuturunen** [MatthewInch/UI24RBridge#1]
Hi there! Thanks for sharing this! So far all implemented features seems to work fine, but not channels that are stereo linked. If you move fader of a channel that's "member" of linked channels, the other channel doesn't change it's volume. Maybe this is something you can fix?

**Comment by MatthewInch** [comment]
Hi,

Thanks the feedback. You are right, the stereo link is not implemented yet. I put it to the list 🙂
I think the next steps:

  *   implement mute function
  *   add change layout feature (I think is important if you want to use the view groups independently.
  *   implement stereo link 😄

If you have any other idea what I need please let me know.

Thank you and best regards
Mátyás

________________________________
Feladó: rikuturunen <notifications@github.com>
Elküldve: 2020. január 14., kedd 17:45
Címzett: MatthewInch/UI24RBridge <UI24RBridge@noreply.github.com>
Másolatot kap: Subscribed <subscribed@noreply.github.com>
Tárgy: [MatthewInch/UI24RBridge] Stereo linking not working properly (#1)


Hi there! Thanks for sharing this! So far all implemented features seems to work fine, but not channels that are stereo linked. If you move fader of a channel that's "member" of linked channels, the other channel doesn't change it's volume. Maybe this is something you can fix?

**Comment by rikuturunen** [comment]
Sounds great! Couple other feature requests (since you asked for it):
- support for mute groups toggling
- suppor for global tap tempo

I guess both of those would require user to somehow assign desired button
of the controller, so it would propably need to go to the config file?

ti 14. tammik. 2020 klo 19.53 MatthewInch <notifications@github.com>
kirjoitti:

**Comment by MatthewInch** [comment]
the stereo link is implemented
