### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by jord4231** [MatthewInch/UI24RBridge#11]
I've followed the directions on how to install ui24bridge on raspberry pi. I am a little confused about running the application. Is it working yet?
Thank you

**Comment by MatthewInch** [comment]
Unfortunately the library, that i used for midi messages, has a bug on linux. In 64bit os the messages can be sent to the controller but in the input side, the first byte of the mesages are lost. Time to time i try to find a solution, currently it is not working

**Comment by Qbort** [comment]
Fixed in #17
