### ISSUE TITLE
Toggling solo & mute lights up wrong button on controller

### ISSUE THREAD

**Issue by rikuturunen** [MatthewInch/UI24RBridge#3]
Just tested out the 0.6.0. Mute and solo functions are working (thanks!), but toggling them on seems to light up wrong button on the controller. Seems like the light is off by one channel. Meaning, if I mute channel #3, the mute light goes on at channel #2 on my controller. On UI all looks good, correct channel goes to mute.

Controller I'm using is X-Touch Compact, running in MCU mode.

**Comment by MatthewInch** [comment]
Thanks the feedback.  I think i know what is the problem with the leds. We have two types of channel number: one of that the real (0-24) one of a virtual (0-7) virtual represent the controller channel number. I think I changed this when toggle the leds after a button press

________________________________
Feladó: rikuturunen <notifications@github.com>
Elküldve: 2020. január 17., péntek 8:25
Címzett: MatthewInch/UI24RBridge <UI24RBridge@noreply.github.com>
Másolatot kap: Subscribed <subscribed@noreply.github.com>
Tárgy: [MatthewInch/UI24RBridge] Toggling solo & mute lights up wrong button on controller (#3)


Just tested out the 0.6.0. Mute and solo functions are working (thanks!), but toggling them on seems to light up wrong button on the controller. Seems like the light is off by one channel. Meaning, if I mute channel #3<https://github.com/MatthewInch/UI24RBridge/issues/3>, the mute light goes on at channel #2<https://github.com/MatthewInch/UI24RBridge/issues/2> on my controller. On UI all looks good, correct channel goes to mute.

Controller I'm using is X-Touch Compact, running in MCU mode.

**Comment by MatthewInch** [comment]
It is fixed :)
