### ISSUE TITLE
[QUESTION] controller compatibility

### ISSUE THREAD

**Issue by othmar52** [MatthewInch/UI24RBridge#6]
We consider to replace our two `Zoom R-24` with an `Ui24r`+ `X-Touch mini` for multitrack-recording our jam sessions.

Currently we are in the evaluation process what hardware we need, what do we want to have visualized and where, what do we want to control by a hardware controller, etc.
At this point our whishes/requirements for the hardware-bridge seems to be pretty small:
 * a button for start/stop recording
 * an indicator for the recording state (currently recording or not recording)
 * a fader or encoder for master volume (no indication/vu-meter required)
  
now i do some resarch for the smallest controller-hardware that fits those needs and came across "Behringer X-Touch mini".
As it supports MC it seems to be compatible to your UI24RBridge, right?
We need a network-connected pc to use your project, right? or did you find a way to upload your software directly to the ui24r?
do you have any recommendations for any kind of hardware controller that fits our needs?  
thanks for your feedback!

**Comment by MatthewInch** [comment]
- I think it should work with X-Touch mini but I have never tested it. 
- No way to upload to the mixer thus you need an additional computer/mini computer etc.
