### ISSUE TITLE
Mute Group and Mute VCA after reconnect???

### ISSUE THREAD

**Issue by muziker-git** [MatthewInch/UI24RBridge#7]
Release 0.6.11, firmware UI24r is 3.0 and 3.3.
After reconnect Muted groups and VCA`s is opened, but X-Toch knobs is colored.
I use release 0.6.10, but I like 0.6.11
Please help!

**Comment by muziker-git** [comment]
+
If activate muted groups in browser - knobs on X-Touch is colored, but after reconnect in release 0.6.11 this groups is opened again, but X_Touch's knobs colored...

**Comment by muziker-git** [comment]
Version new 0.7.0.
Trouble is old.
Automation buttons (Read/Off, Write, Trim, Touch, Latch, Group) after reconnect is not correct.
VCA mute knob on X-Touch after reconnect is not correct.
I think stable version fixed this problems.

**Comment by MatthewInch** [comment]
Hello muziker-git,
sorry for the late reply but I hope I will have time to check these bugs soon. (and of course fix that :D)

**Comment by muziker-git** [comment]
I like your solution.
It's a true "audio desk philosophy".
I wait for next releases.
And I hope for your success.

**Comment by MatthewInch** [comment]
I fixed the mute groups, Mute FX, Mute all leads problem during reconnection.
Thanks for the feedback
The next release (It may be called v0.7.2) will contain that.

**Comment by cglaesser** [comment]
Hi Matthew,
how do you connect the x-Touch and UI24R? Midi Cable or Ethernet?
THX, Chris

**Comment by cglaesser** [comment]
Hi Matthew,
how do you connect the x-Touch and UI24R? USB Cable or Ethernet?
THX, Chris

**Comment by bostiko** [comment]
Hi, you need a computer with this app and x-Touch connected. Computer is connected normally to UI24R (via wifi/cable). This program makes bridge between X-Touch and UI24R.

**Comment by cglaesser** [comment]
Hi, THX. Do I need an extra rtp midi driver installed?

best regards

Chris

 
 

Gesendet: Freitag, 23. Juli 2021 um 09:26 Uhr
Von: "bostiko" ***@***.***>
An: "MatthewInch/UI24RBridge" ***@***.***>
Cc: "cglaesser" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [MatthewInch/UI24RBridge] Mute Group and Mute VCA after reconnect??? (#7)


 

Hi, you need a computer with this app and x-Touch connected. Computer is connected normally to UI24R (via wifi/cable). This program makes bridge between X-Touch and UI24R.

**Comment by bostiko** [comment]
No, the only driver needed is the one for the X-touch USB midi and this is installed automatically.

**Comment by cglaesser** [comment]
THX, i will try it again, first time i got a midi error, but the x-touch wasn´t connected via usb cable, and also not directly connected to the Computer (via switsch).

Best regards

Chris

 
 

Gesendet: Freitag, 23. Juli 2021 um 09:45 Uhr
Von: "bostiko" ***@***.***>
An: "MatthewInch/UI24RBridge" ***@***.***>
Cc: "cglaesser" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [MatthewInch/UI24RBridge] Mute Group and Mute VCA after reconnect??? (#7)


 

No, the only driver needed is the one for the X-touch USB midi and this is installed automatically.

**Comment by bostiko** [comment]
I have added the detailed setup explanation to the [wiki page](https://github.com/MatthewInch/UI24RBridge/wiki/Behringer-X-Touch-setup)

**Comment by cglaesser** [comment]
Thank a lot, i will test it in the evening.

 

Best Regards

Chris

 
 

Gesendet: Freitag, 23. Juli 2021 um 10:36 Uhr
Von: "bostiko" ***@***.***>
An: "MatthewInch/UI24RBridge" ***@***.***>
Cc: "cglaesser" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [MatthewInch/UI24RBridge] Mute Group and Mute VCA after reconnect??? (#7)


 

I have added the detailed setup explanation to the wiki page
