### ISSUE TITLE
Query: live use

### ISSUE THREAD

**Issue by brendan-pike** [MatthewInch/UI24RBridge#8]
I'm fairly new to midi / daw use but I'm wondering it its possible for this to be used in a live environment, and if so how. Currently I only use the HTML interface live.

**Comment by bostiko** [comment]
This SW is intended to Live usage. Buy the X-Touch, connect it to the computer and enoy :)

This is photo from one of my live gig:
![Photo from one of my live gig](https://user-images.githubusercontent.com/23098949/126757989-f4883285-c94d-43dc-9fab-c48caa3aa7fa.jpg)

**Comment by elio40** [comment]
hola desde Bolivia
como puedo asignar el paneo en las perillas de la x touch
